### ISSUE TITLE
missing license?

### ISSUE THREAD

**Issue by jquatier** [eltonjuan/test#1]

**Comment by cpeddecord** [comment]
+1

**Comment by eltonjuan** [comment]
Just pushed this over to my legal team, they drafted up a license real quick. Committed straight to master as we need to be quick with this one. Once again, thank you to @jquatier for his LOC to reducing the LOE on legal tasks moving forward. 

Looking forward to shipping 🚚  great work in 2017 📦 ! 

All the best, 
Elton Juan
Test LLC

**Comment by jquatier** [comment]
Thanks for the fast turnaround! Let's circle back on this tomorrow and discuss next steps.
